[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "trietool"
path = "trietool.rs"

[dependencies]
datrie-clib = { version = "0.1.0", path = "../src/clib" }
libc = "0.2.149"
